---

# 보안 통제 대상 파일 및 디렉터리 경로
path_passwd: '/etc/passwd'
path_shadow: '/etc/shadow'
path_hosts: '/etc/hosts'
path_services: '/etc/services'
path_root_dir: '/root'
path_etc_profile: '/etc/profile'

# 우회 인증 전역 설정 파일 경로
path_hosts_equiv: '/etc/hosts.equiv'