---
- name: "1. Master Node Control Plane 설정"
  ansible.builtin.import_tasks: 1_control_plane.yml
  when: k8s_apply_control_plane | bool

- name: "2. Master Node API Server 설정"
  ansible.builtin.import_tasks: 2_api_server.yml
  when: k8s_apply_api_server | bool

- name: "3. Master Node etcd 설정"
  ansible.builtin.import_tasks: 3_etcd.yml
  when: k8s_apply_etcd | bool

- name: "4. Worker Node Kubelet 설정"
  ansible.builtin.import_tasks: 4_kubelet.yml
  when: k8s_apply_kubelet | bool

- name: "5. 클러스터 보안 정책(PSA) 설정"
  ansible.builtin.import_tasks: 5_policies.yml
  when: k8s_apply_policies | bool
