---
- name: 보고서 출력 디렉터리 생성 (존재하지 않을 경우)
  ansible.builtin.file:
    path: "{{ report_output_dir }}"
    state: directory
    mode: "{{ file_mode_755 }}"
  delegate_to: localhost
  check_mode: no

- name: 보안조치 결과 보고서 최종 파일 생성
  ansible.builtin.template:
    src: report.md.j2
    dest: "{{ report_output_dir }}/{{ report_filename }}"
    mode: "{{ file_mode_644 }}"
  delegate_to: localhost
  check_mode: no