[openstack_nodes]
controller01
compute01
storage01

[network_gear]
router01
switch01

[network_gear:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=community.routeros.routeros
# ansible_host=198.51.100.10
# ansible_user=automation_user

; [lab]
; localhost ansible_connection=local
