[db]
# db1 ansible_host=10.0.0.20

[docker]
# docker1 ansible_host=10.0.0.30

[k8s_control_plane]
# control-plane-1 ansible_host=10.0.0.40
k8s-control ansible_host=32.192.180.28 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/k8s-test-key.pem k8s_role=control_plane k8s_private_ip=172.31.40.55

[k8s_worker]
# worker-1 ansible_host=10.0.0.41
k8s-worker ansible_host=3.94.122.8 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/k8s-test-key.pem k8s_role=worker k8s_private_ip=172.31.35.160
[k8s:children]
k8s_control_plane
k8s_worker
[keystone]
# controller1 ansible_host=10.0.0.10

[nova]
# controller1 ansible_host=10.0.0.10
# compute1 ansible_host=10.0.0.11

[cinder]
# controller1 ansible_host=10.0.0.10
# storage1 ansible_host=10.0.0.12

[glance]
# controller1 ansible_host=10.0.0.10

[neutron]
# controller1 ansible_host=10.0.0.10
# network1 ansible_host=10.0.0.13

[horizon]
# controller1 ansible_host=10.0.0.10
