[keystone]
# controller1 ansible_host=10.0.0.10

[nova]
# controller1 ansible_host=10.0.0.10
# compute1 ansible_host=10.0.0.11

[cinder]
# controller1 ansible_host=10.0.0.10
# storage1 ansible_host=10.0.0.12

[glance]
# controller1 ansible_host=10.0.0.10

[neutron]
# controller1 ansible_host=10.0.0.10
# network1 ansible_host=10.0.0.13

[horizon]
# controller1 ansible_host=10.0.0.10
