---
- name: "KVM 계정 보안 정책 포함"
  ansible.builtin.import_tasks: accounts.yml
  tags:
    - kvm_accounts

- name: "KVM 세션 timeout 정책 포함"
  ansible.builtin.import_tasks: session_timeout.yml
  tags:
    - kvm_session_timeout

- name: "KVM IP 접근 제한 정책 포함"
  ansible.builtin.import_tasks: ip_restrict.yml
  tags:
    - kvm_ip_restrict

- name: "KVM default bridge 정책 포함"
  ansible.builtin.import_tasks: default_bridge.yml
  tags:
    - kvm_default_bridge

- name: "KVM 로그 백업 정책 포함"
  ansible.builtin.import_tasks: log_backup.yml
  tags:
    - kvm_log_backup
