---
- name: "Ceph keyring 권한 정책 포함"
  ansible.builtin.import_tasks: keyring.yml
  tags:
    - ceph_keyring

- name: "Ceph SSH key 권한 정책 포함"
  ansible.builtin.import_tasks: ssh_keys.yml
  tags:
    - ceph_ssh_keys

- name: "Ceph config 권한 정책 포함"
  ansible.builtin.import_tasks: config.yml
  tags:
    - ceph_config

- name: "CephX 인증 정책 포함"
  ansible.builtin.import_tasks: auth.yml
  tags:
    - ceph_auth

- name: "Ceph 관리자 계정 정책 포함"
  ansible.builtin.import_tasks: admin_user.yml
  tags:
    - ceph_admin_user
