---
network_security_mode: audit

network_hardening_allowed_management_cidrs: []
network_hardening_disabled_services:
  - telnet
  - ftp
  - www
  - www-ssl
  - api
  - api-ssl
network_hardening_ssh_service_name: ssh
network_hardening_winbox_service_name: winbox
network_hardening_session_timeout_users: []
network_hardening_session_timeout: 10m
network_hardening_session_inactivity_policy: logout
network_hardening_disable_snmp: true
network_hardening_unused_port_shutdown_enabled: false
network_hardening_unused_interfaces: []
network_hardening_rp_filter_enabled: false
network_hardening_rp_filter_mode: loose
network_hardening_dos_protection_enabled: false
network_hardening_dos_rules: []
network_hardening_default_drop_enabled: false
network_hardening_default_drop_confirmed: false
network_hardening_drop_logging_enabled: false
