---
network_security_mode: audit

neutron_security_api_cert_enabled: false
neutron_security_api_cert_confirmed: false
neutron_security_tls_enabled: false
neutron_security_tls_confirmed: false
neutron_security_config_path: ""
neutron_security_cert_file: ""
neutron_security_key_file: ""
neutron_security_ca_file: ""
neutron_security_service_name: ""
