---
- name: "Storage root SSH 제한 정책 포함"
  ansible.builtin.import_tasks: root_ssh.yml
  tags:
    - storage_root_ssh

- name: "Storage 패스워드 복잡도 정책 포함"
  ansible.builtin.import_tasks: password_complexity.yml
  tags:
    - storage_password_complexity

- name: "Storage 계정 잠금 정책 포함"
  ansible.builtin.import_tasks: account_lock.yml
  tags:
    - storage_account_lock

- name: "Storage 패스워드 사용 기간 정책 포함"
  ansible.builtin.import_tasks: password_age.yml
  tags:
    - storage_password_age
