---
- name: "[1-2] Docker 버전 패치 및 그룹 사용자 제한"
  include_tasks: 1_version_and_users.yml

- name: "[3-8] Docker Audit(감사) 규칙 설정"
  include_tasks: 2_audit_config.yml
  when: docker_apply_audit_config | bool

- name: "[9-13] 주요 파일 소유권 및 권한 설정"
  include_tasks: 3_file_permissions.yml

- name: "[14] 컨테이너 추가 권한 획득 제한 (Daemon 설정)"
  include_tasks: 4_daemon_security.yml
  when: docker_apply_daemon_security | bool

- name: "[15-17] 컨테이너 런타임 보안 점검"
  include_tasks: 5_container_runtime_checks.yml
  when: docker_enable_runtime_container_checks | bool
