---
- name: Restart Docker
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: restarted

- name: Reload Docker Daemon
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ docker_service_name }}"
    state: reloaded

- name: Restart Auditd
  ansible.builtin.service:
    name: "{{ auditd_service_name }}"
    state: restarted
    enabled: true
  ignore_errors: true
