---

# [파일 소유자 및 그룹 정책]
file_owner_root: 'root'
file_group_root: 'root'

# [파일 및 디렉터리 접근 권한(Mode) 정책]
# 일반 설정 파일은 소유자 외 쓰기 방지 (644)
file_mode_644: '0644'

# 암호 해시 등 민감 파일은 관리자 전용 보호 (400)
file_mode_400: '0400'

# 중요 디렉터리는 타 사용자 접근 원천 차단 (700)
dir_mode_700: '0700'
