    
- name: Include account hardening
  ansible.builtin.include_tasks: account.yml
    tags: [os, account]

- name: Include file/config hardening
  ansible.builtin.include_tasks: files.yml
    tags: [os, files]

- name: Include audits
  ansible.builtin.include_tasks: audit.yml
    tags: [os, audit]
