---
- name: Apply KISA Keystone security controls
  hosts: keystone
  become: true
  vars:
    apply_policy: false
  check_mode: "{{ not (apply_policy | bool) }}"
  roles:
    - role: keystone-security
      tags: [keystone, identity, openstack]

- name: Apply KISA Nova security controls
  hosts: nova
  become: true
  vars:
    apply_policy: false
  check_mode: "{{ not (apply_policy | bool) }}"
  roles:
    - role: nova-security
      tags: [nova, compute, openstack]

- name: Apply KISA Cinder security controls
  hosts: cinder
  become: true
  vars:
    apply_policy: false
  check_mode: "{{ not (apply_policy | bool) }}"
  roles:
    - role: cinder-security
      tags: [cinder, block-storage, openstack]

- name: Apply KISA Glance security controls
  hosts: glance
  become: true
  vars:
    apply_policy: false
  check_mode: "{{ not (apply_policy | bool) }}"
  roles:
    - role: glance-security
      tags: [glance, image-storage, openstack]

- name: Apply KISA Neutron security controls
  hosts: neutron
  become: true
  vars:
    apply_policy: false
  check_mode: "{{ not (apply_policy | bool) }}"
  roles:
    - role: neutron-security
      tags: [neutron, networking, openstack]
