---
- name: "Aolda 2026 인프라 OS 보안 강화 정책 일괄 적용"
  hosts: os_nodes         # 실행 대상 호스트 그룹
  become: yes             # 정책 주입을 위해 root 권한 강제 (sudo)
  gather_facts: yes       # OS 버전 감지 및 조건문 처리를 위해 팩트 수집 필수

  vars:
    # =========================================================
    # [공통 제어 변수]
    # =========================================================
    apply_policy: false   # 명령어에 -e 옵션을 생략해도 기본적으로 점검(Dry-run) 모드로 동작하게 하여 사고 방지

    # =========================================================
    # 1.1 계정 및 인증 보안 정책
    # =========================================================
    path_sshd_config: "/etc/ssh/sshd_config"
    sshd_permit_root_login: "no"
    sshd_password_authentication: "yes"
    os_pass_max_days: 90
    pam_deny_count: 5
    pam_unlock_time: 600
    pam_pwquality_minlen: 8
    pam_pwquality_lcredit: -1
    pam_pwquality_ucredit: -1
    pam_pwquality_dcredit: -1
    pam_pwquality_ocredit: -1

    # =========================================================
    # 1.2 파일 시스템 및 접근 제어 정책
    # =========================================================
    os_scan_fstypes: "-fstype ext4 -o -fstype xfs"
    os_scan_exclude_paths: "-path /tmp -prune -o -path /var/tmp -prune"
    allowed_ssh_ips:
      - "10.110.0.0/16"
      - "10.113.0.0/16"

    # =========================================================
    # 1.3 시스템 서비스 및 타임 동기화 정책
    # =========================================================
    system_timezone: "Asia/Seoul"
    legacy_ntp_packages:
      - "ntp"
      - "chrony"
    package_timesyncd: "systemd-timesyncd"
    service_timesyncd: "systemd-timesyncd"

    # =========================================================
    # 1.4 공격 표면 최소화 정책
    # =========================================================
    unnecessary_packages:
      - "finger"
      - "tftpd"
      - "talk"
      - "ntalk"
      - "rsh-server"
      - "rsh-client"
      - "nis"
      - "sendmail"
      - "autofs"
    xinetd_vulnerable_services:
      - "echo"
      - "discard"
      - "daytime"
      - "chargen"
      - "rlogin"
      - "rsh"
      - "rexec"
      - "finger"
      - "tftp"
      - "talk"
      - "ntalk"
      - "rstatd"
    standalone_services_to_disable:
      - "nfs-server"
      - "rpcbind"
      - "autofs"
      - "sendmail"

  check_mode: "{{ not (apply_policy | bool) }}"

  roles:
    - role: ../roles/os-security
