---
- name: "KVM security baseline"
  hosts: kvm_hosts
  gather_facts: true
  become: true
  roles:
    - role: kvm-account-audit

- name: "Ceph security baseline"
  hosts: ceph_hosts
  gather_facts: true
  become: true
  roles:
    - role: ceph-security-baseline

- name: "Storage security baseline"
  hosts: storage_hosts
  gather_facts: true
  become: true
  roles:
    - role: storage-security-baseline
